# -*- coding: utf-8 -*-
"""Expression Detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yFUZg6jnrzDACHkxP_7mi03dGvnhdxZb
"""

pip install streamlit deepface opencv-python pillow tf-keras
import streamlit as st
import cv2
import numpy as np
from deepface import DeepFace
from PIL import Image

st.set_page_config(
    page_title="AI Emotion Detector",
    page_icon="🧠",
    layout="centered"
)

st.title("🧠 AI Emotion Detection System")
st.write("This AI detects human emotions automatically using facial expressions.")

st.divider()

# Camera input
img_file = st.camera_input("📸 Look at the camera")

if img_file is not None:
    # Convert image
    image = Image.open(img_file)
    frame = np.array(image)

    with st.spinner("Analyzing facial expressions..."):
        try:
            result = DeepFace.analyze(
                img_path=frame,
                actions=["emotion"],
                enforce_detection=False
            )

            emotion = result[0]["dominant_emotion"]
            emotion_scores = result[0]["emotion"]

            st.success(f"🎯 Detected Emotion: **{emotion.upper()}**")

            st.subheader("📊 Emotion Confidence")
            st.bar_chart(emotion_scores)

            st.image(frame, caption="Captured Face", use_column_width=True)

        except Exception as e:
            st.error("Face not detected properly. Please try again.")