# -*- coding: utf-8 -*-
"""Expression Detector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yFUZg6jnrzDACHkxP_7mi03dGvnhdxZb
"""

import streamlit as st
import cv2
import numpy as np
from deepface import DeepFace
from PIL import Image

st.set_page_config(
    page_title="AI Emotion Detector",
    page_icon="😊",
    layout="centered"
)

st.title("😊 AI Emotion Detector")
st.write("This AI detects human emotions using facial expressions.")

# Camera input
img_file = st.camera_input("Capture your face")

if img_file is not None:
    image = Image.open(img_file)
    frame = np.array(image)

    st.image(frame, caption="Captured Image", use_container_width=True)

    with st.spinner("Analyzing emotion..."):
        try:
            result = DeepFace.analyze(
                img_path=frame,
                actions=["emotion"],
                enforce_detection=False
            )

            emotions = result[0]["emotion"]
            dominant = result[0]["dominant_emotion"]
            confidence = emotions[dominant]

            st.success(f"🧠 Emotion Detected: **{dominant.upper()}**")
            st.write(f"Confidence: **{confidence:.2f}%**")

            st.subheader("All Emotion Scores")
            st.bar_chart(emotions)

        except Exception as e:
            st.error("Face not detected clearly. Please try again.")